const { User, validate, Loginvalidate } = require("../model/UserSchema");
const bcrypt = require("bcrypt");
const { Product, productvalidate } = require("../model/ProductSchema");
const stripe = require('stripe')(process.env.STRIPE_PRIVATE_KEY);

module.exports = {
  usersignup: async (req, res) => {
    try {
      // console.log(req.body);
      const { error } = validate(req.body);
      if (error)
        return res.status(400).send({ message: error.details[0].message });
      const user = await User.findOne({ email: req.body.email });
      if (user)
        return res
          .status(409)
          .send({ message: "User with given mailid Already exist" });
      const salt = await bcrypt.genSalt(Number(process.env.SALT));
      const hashpassword = await bcrypt.hash(req.body.password, salt);

      await User.create({ ...req.body, password: hashpassword });

      res.status(201).send({ message: "User Created Successfully" });
    } catch (error) {
      return res.status(500).send({ message: "Internal Server Error" });
    }
  },
  userlogin: async (req, res) => {
    try {
      //console.log(req.body);
      const { error } = Loginvalidate(req.body);
      if (error)
        return res.status(400).send({ message: error.details[0].message });
      const user = await User.findOne({ email: req.body.email });
      if (!user)
        return res.status(401).send({ message: "Invalid Email or Password" });
      const validpassword = await bcrypt.compare(
        req.body.password,
        user.password
      );
      if (!validpassword)
        return res.status(401).send({ message: "Invalid Email or Password" });
      const token = user.generateAuthToken();
      res.status(201).send({ data: token, message: "Loggin Successfully" });
    } catch (error) {
      return res.status(500).send({ message: "Internal Server Error" });
    }
  },
  addproducts: async (req, res) => {
    try {
      const { error } = productvalidate(req.body);
      if (error)
        return res.status(400).send({ message: error.details[0].message });

      const existingProduct = await Product.findOne({
        productname: req.body.productname,
      });
      if (existingProduct)
        return res.status(409).send({ message: "Product Already Exists" });

      let productimageUrl;
      if (req.file && req.file.path) {
        // Use the URL generated by Cloudinary
        productimageUrl = req.file.path;
      }

      // Create new product document
      const newProduct = await Product.create({
        productname: req.body.productname,
        price: req.body.price,
        productimage: productimageUrl, // Store Cloudinary URL here
      });

      res
        .status(201)
        .send({ newProduct, message: "Product Added Successfully" });
    } catch (error) {
      console.error(error);
      return res.status(500).send({ message: "Internal Server Error" });
    }
  },
  listProducts: async (req, res) => {
    try {
      const allproducts = await Product.find();
      if (allproducts.length === 0) {
        return res.status(400).send({ message: "products NOt available" });
      }
      res
        .status(201)
        .send({ allproducts, message: "Gets all the products Successfully" });
    } catch (error) {
      return res.status(500).send({ message: "Internal Server Error" });
    }
  },
  stripePayment: async (req, res) => {
    try {
        const session = await stripe.checkout.sessions.create({
            payment_method_types: ["card"], 
            mode: "payment", 
            line_items: req.body.items.map(item => {
                return {
                    price_data: {
                        currency: "inr",
                        product_data: {
                            name: item.name
                        },
                        unit_amount: item.price * 100 
                    },
                    quantity: item.quantity
                };
            }),
            success_url: `http://localhost:3000/success`,
            cancel_url: `http://localhost:3000/cancel`
        });
        res.json({ url: session.url });
    } catch (error) {
        console.error(error);
        return res.status(500).send({ message: "Internal Server Error" });
    }

}
};
